services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_management_app
    image: game_management_app_image
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - game_management_network
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000  # Run Laravel's built-in server on port 8000

  db:
    image: mysql:8.0.41
    container_name: games_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - game_management_network

networks:
  game_management_network:
    driver: bridge

volumes:
  db_data:
    driver: local
